# Generated by Django 5.1 on 2024-11-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='category',
            name='restaurants',
            field=models.ManyToManyField(related_name='category', to='restaurant.restaurant'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(related_name='ingredients', to='restaurant.dish'),
        ),
    ]
